# Generated by Django 2.0.2 on 2018-02-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupon_url', models.URLField()),
                ('expiration_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('group_size', models.PositiveIntegerField()),
                ('members_needed', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
