# Generated by Django 2.0.2 on 2018-03-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0002_userrequests_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
