# Generated by Django 2.0.2 on 2018-04-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0003_userrequests_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='groupon_url',
            field=models.URLField(default='groupon.com'),
        ),
    ]
